- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_password: ExpenseApp@1
  tasks:
  - name: installing packages
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
      - cryptography
      - pyMySQL

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: mysql start and enable mysql
    ansible.builtin.service:
      name: mysqld
      service: started
      enable: yes
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host:  172.31.21.147
    register: mysql_info
    ignore_errors: true
  - name: output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true
